define `related_name` for `canceled_by`
... to eliminate the following failure while applying migrations:
```
+ osh/hub/manage.py migrate
SystemCheckError: System check identified some issues:

ERRORS:
hub.Task.cancelled_by: (fields.E304) Reverse accessor 'User.task_set' for 'hub.Task.cancelled_by' clashes with reverse accessor for 'hub.Task.owner'.
	HINT: Add or change a related_name argument to the definition for 'hub.Task.cancelled_by' or 'hub.Task.owner'.
hub.Task.owner: (fields.E304) Reverse accessor 'User.task_set' for 'hub.Task.owner' clashes with reverse accessor for 'hub.Task.cancelled_by'.
	HINT: Add or change a related_name argument to the definition for 'hub.Task.owner' or 'hub.Task.cancelled_by'.
```

Related: https://github.com/release-engineering/kobo/pull/271
Related: https://github.com/openscanhub/openscanhub/pull/317
Closes: https://github.com/release-engineering/kobo/pull/273